import { HorizontalBox, VerticalBox, ComboBox, ScrollView, Button } from "std-widgets.slint";

export component MainWindow inherits Window {
    in property <image> image-data;
    out property <int> image-size: 0;
    in-out property <float> scale: 1;
    private property <length> image-width-scaled: image-data.width * scale * 1px;
    private property <length> image-height-scaled: image-data.height * scale * 1px;

    // chamge later to in or to out
   
    title: "Slint Image Filter Integration Example";
    // preferred-width: 800px;
    // preferred-height: 600px;

    VerticalBox {
        HorizontalBox {
            Button {
                text: "Original size" + scale;
                clicked => {
                    image-size = 0;
                }
            }

            Button {
                text: "Fit to window";
                clicked => {
                    image-size = 1;
                }
            }
        }

        if (image-size == 1): HorizontalBox {
            padding-left: (parent.width > image-width-scaled) ? (parent.width - image-width-scaled) / 2 : 0px;
            Flickable {
                viewport-width: image-width-scaled;
                viewport-height: image-height-scaled;
                TouchArea {
                    scroll-event(event) => {
                        if (event.delta-y > 0) {
                            root.scale += 0.5;
                        } else if (root.scale > 0.5) {
                            root.scale -= 0.5;
                        }
                        accept
                    }
                    Image {
                        source: image-data;
                        image-fit: cover;
                        width: image-width-scaled;
                        height: image-height-scaled;
                    }
                }
            }
        }

        if (image-size == 0): Image {
            source: image-data;
            image-fit: contain;
        }
    }
}
