import { HorizontalBox, VerticalBox, ComboBox, ScrollView, Button } from "std-widgets.slint";

export component MainWindow inherits Window {
    in property <image> image-data;
    out property <int> image-size: 0;

    title: "Slint Image Filter Integration Example";
    // preferred-width: 800px;
    // preferred-height: 600px;

    VerticalBox {
        HorizontalBox {
            Button {
                text: "Original size";
                clicked => {
                    image-size = 0;
                }
            }

            Button {
                text: "Fit to window";
                clicked => {
                    image-size = 1;
                }
            }
        }

        if (image-size == 1): HorizontalBox {
            padding-left: (parent.width > image-data.width * 1px) ? (parent.width - image-data.width * 1px) / 2 : 0px;
            Flickable {
                //image-fit: preserve; for original size
            //scrollview's viewport-width and height needed for scroll to appear
            viewport-width: image-data.width * 1px;
                viewport-height: image-data.height * 1px;
                // width: (parent.width > self.viewport-width) ? image-data.width * 1px : parent.width;
            // padding-left: (parent.width > self.viewport-width) ? (parent.width - self.viewport-width) / 2 : 0px;
            Image {
                    source: image-data;
                    image-fit: preserve;
                }
            }
        }

        if (image-size == 0): Image {
            source: image-data;
            image-fit: contain;
        }
    }
}
